### ISSUE TITLE
Return values from some functions not used

### ISSUE THREAD

**Issue by xambroz** [radareorg/r2cutter#10]
Hello,
compilation reports issue that the return values from some functions are not handled properly. This could cause some race condition issues or even data loss when writing.

[ 22%] Building CXX object CMakeFiles/r2cutter.dir/widgets/ExportsWidget.cpp.o
/usr/lib64/ccache/g++ -DCUTTER_ENABLE_GRAPHVIZ -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING -DCUTTER_SOURCE_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Dr2cutter_EXPORTS -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu -IBUILD/r2cutter-0.1.1/src -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu/r2cutter_autogen/include -IBUILD/r2cutter-0.1.1/src/core -IBUILD/r2cutter-0.1.1/src/widgets -IBUILD/r2cutter-0.1.1/src/common -IBUILD/r2cutter-0.1.1/src/plugins -IBUILD/r2cutter-0.1.1/src/menus -IBUILD/r2cutter-0.1.1/src/. -isystem /usr/include/graphviz -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/libr -isystem /usr/include/libr/sdb -isystem /usr/include/capstone -isystem /usr/include/KF5/KSyntaxHighlighting -isystem /usr/include/KF5 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fvisibility=hidden   -Wall -Wextra -fPIC -std=gnu++11 -o CMakeFiles/r2cutter.dir/widgets/ExportsWidget.cpp.o -c BUILD/r2cutter-0.1.1/src/widgets/ExportsWidget.cpp
BUILD/r2cutter-0.1.1/src/widgets/ConsoleWidget.cpp: In member function 'void ConsoleWidget::sendToStdin(const QString&)':
BUILD/r2cutter-0.1.1/src/widgets/ConsoleWidget.cpp:251:10: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Wunused-result]
  251 |     write(stdinFile, (input + "\n").toStdString().c_str(), input.size() + 1);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BUILD/r2cutter-0.1.1/src/widgets/ConsoleWidget.cpp: In member function 'void ConsoleWidget::redirectOutput()':
BUILD/r2cutter-0.1.1/src/widgets/ConsoleWidget.cpp:463:9: warning: ignoring return value of 'int pipe(int*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  463 |     pipe(redirectPipeFds);
      |     ~~~~^~~~~~~~~~~~~~~~~

**Comment by xambroz** [comment]
You are monster @pancake ... I was just wondering whether or not I have submitted, and it is already fixed :D.
Thank you

**Comment by trufae** [comment]
The CI seems to be broken, but unrelated to those changes, there are some QT changes that broke the build. im sorry because this repo have been very sadly badly maintained, hope to clean all warnings before the next release, im not in the mood to do much c++/qt stuff but any contribution is welcome!

thanks for reporting!
