### ISSUE TITLE
src/common/Decompiler.cpp:60:47: warning: missing initializer for member 

### ISSUE THREAD

**Issue by xambroz** [radareorg/r2cutter#13]
Compilation of the 0.1.1 release reports this warning

[ 85%] Building CXX object CMakeFiles/r2cutter.dir/common/Decompiler.cpp.o
/usr/lib64/ccache/g++ -DCUTTER_ENABLE_GRAPHVIZ -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING -DCUTTER_SOURCE_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Dr2cutter_EXPORTS -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu -IBUILD/r2cutter-0.1.1/src -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu/r2cutter_autogen/include -IBUILD/r2cutter-0.1.1/src/core -IBUILD/r2cutter-0.1.1/src/widgets -IBUILD/r2cutter-0.1.1/src/common -IBUILD/r2cutter-0.1.1/src/plugins -IBUILD/r2cutter-0.1.1/src/menus -IBUILD/r2cutter-0.1.1/src/. -isystem /usr/include/graphviz -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/libr -isystem /usr/include/libr/sdb -isystem /usr/include/capstone -isystem /usr/include/KF5/KSyntaxHighlighting -isystem /usr/include/KF5 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fvisibility=hidden   -Wall -Wextra -fPIC -std=gnu++11 -o CMakeFiles/r2cutter.dir/common/Decompiler.cpp.o -c BUILD/r2cutter-0.1.1/src/common/Decompiler.cpp
BUILD/r2cutter-0.1.1/src/common/Decompiler.cpp: In lambda function:
BUILD/r2cutter-0.1.1/src/common/Decompiler.cpp:60:47: warning: missing initializer for member 'r_code_annotation_t::end' [-Wmissing-field-initializers]
   60 |             RCodeAnnotation annotationi = { 0 };
      |                                               ^
BUILD/r2cutter-0.1.1/src/common/Decompiler.cpp:60:47: warning: missing initializer for member 'r_code_annotation_t::type' [-Wmissing-field-initializers]
BUILD/r2cutter-0.1.1/src/common/Decompiler.cpp:60:47: warning: missing initializer for member 'r_code_annotation_t::<anonymous>' [-Wmissing-field-initializers]

**Comment by trufae** [comment]
Fixed in master
