### ISSUE TITLE
possible fallthroughs src/widgets/{ExportsWidget.cpp,ImportsWidget.cpp}

### ISSUE THREAD

**Issue by xambroz** [radareorg/r2cutter#14]
Compilation of the release 0.1.1 reports possible fallthrough for these 2 places:

BUILD/r2cutter-0.1.1/src/widgets/ExportsWidget.cpp: In member function 'virtual bool ExportsProxyModel::lessThan(const QModelIndex&, const QModelIndex&) const':
BUILD/r2cutter-0.1.1/src/widgets/ExportsWidget.cpp:122:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
  122 |         if (leftExp.type != rightExp.type)
      |         ^~
BUILD/r2cutter-0.1.1/src/widgets/ExportsWidget.cpp:124:5: note: here
  124 |     case ExportsModel::CommentColumn:
      |     ^~~~

BUILD/r2cutter-0.1.1/src/widgets/ImportsWidget.cpp: In member function 'virtual bool ImportsProxyModel::lessThan(const QModelIndex&, const QModelIndex&) const':
BUILD/r2cutter-0.1.1/src/widgets/ImportsWidget.cpp:144:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
  144 |         if (leftImport.libname != rightImport.libname)
      |         ^~
/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/src/widgets/ImportsWidget.cpp:147:5: note: here
  147 |     case ImportsModel::NameColumn:
      |     ^~~~

Please can you check it is OK or possibly add breaks where it is not supposed to be fall through case.
Thank you.

**Comment by trufae** [comment]
Should be fixed too :) thanks!
