### ISSUE TITLE
Possibly packaging issue with r2cutter-0.1.0_mac.pkg.zip

### ISSUE THREAD

**Issue by hongsolo9** [radareorg/r2cutter#6]
**Environment information**
* Operating System: macOS Mojave
* Cutter version: r2cutter-0.1.0_mac
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: r2cutter-0.1.0_mac.pkg.zip

**Describe the bug**
Found this error message when executing the unzipped r2cutter-5.1.0.pkg file
![Screen Shot 2021-02-01 at 12 33 32 PM](https://user-images.githubusercontent.com/1450374/106416198-cd264080-648b-11eb-937a-aa9bbec93446.png)

**Comment by trufae** [comment]
I can repro, for some reason the script was working fine in local. i'll fix that today :) thanks for testing!

**Comment by trufae** [comment]
Ive uploaded the package built by me in local, so now the .pkg works and you may be able to run it if you have r2 (from git) and libqt installed(from brew). ill improve the packaging in future beta builds.

thanks for the testing
