### ISSUE TITLE
Error in start 

### ISSUE THREAD

**Issue by SergioBG** [radareorg/r2cutter#7]
**Environment information**
* Operating System: Debian testing
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**
When start program from cli with r2cutter show me this error:
r2cutter: symbol lookup error: r2cutter: undefined symbol: r_annotated_code_free

**Comment by trufae** [comment]
You need at least r2-5.1

**Comment by SergioBG** [comment]
Ok , update r2 and all ok , thanks.
